### ISSUE TITLE
peter andreo mendes

### ISSUE THREAD

**Issue by crimag233** [Creeeeger/BtcWalletMiner#1]
hello need a key how it is.
give you the need.

peter andreo mendes
pam,map,smap,amp
crimag.org

peter@crimag.org

**Comment by Creeeeger** [comment]
Hello, do you mean the serial key?

**Comment by Creeeeger** [comment]
mcabar2205

**Comment by crimag233** [comment]
since the last time,hello.


buzz on, the house is on fire,

pass some time... no wallet tranfser!

what can we do?


for the best,peter.

**Comment by Creeeeger** [comment]
Fake BTC wallet miner made

There was the time with these scams and I just wanted to replicate them 

You will never get anything from them 

dark mine is An example
